proj/hh_project/views/login_views.py
from flask import Blueprint, render_template, request, jsonify, session, redirect, url_for
from pymongo import MongoClient

client = MongoClient('mongodb+srv://mino:mino@hanghae.hfuwmwd.mongodb.net/?retryWrites=true&w=majority')
db = client.hanghae

bp = Blueprint('login', __name__, url_prefix='/')


@bp.route('/')
def index():
    if 'ID' in session:
        return redirect(url_for('main.main'))
    return render_template('login.html')

@bp.route('/reigster')
def register():
    return render_template('register.html')

@bp.route('/login', methods=["GET"])
def login_get():
    user_list = list(db.user.find({}, {'_id': False}))
    return jsonify({'user': user_list})


@bp.route('/login/session', methods=["GET", "POST"])
def login_session():
    if request.method == 'POST':
        # 사용자 아이디를 세션에 저장 및  main으로 리다이렉트
        session.clear();
        session['ID'] = request.form['id_give']
        return redirect(url_for('main.main'))


@bp.route('/logout')
def logout():
    # 사용자 아이디를 세션에서 제거하고 /로 리다이렉트
    session.pop('ID', None)
    return redirect(url_for('login.index'))

proj/hh_project/views/register_views.py
from flask import Blueprint, render_template, request, jsonify
from pymongo import MongoClient

client = MongoClient('mongodb+srv://mino:mino@hanghae.hfuwmwd.mongodb.net/?retryWrites=true&w=majority')
db = client.hanghae

bp = Blueprint('auth', __name__, url_prefix='/register')


@bp.route('/')
def register():
    return render_template('register.html')


@bp.route('/post', methods=["POST"])
def register_post():
    # receive data from html
    id_receive = request.form['id_give']
    pw_receive = request.form['pw_give']
    image_receive = request.form['image_give']

    # DB data set
    doc = {
        'ID': id_receive,
        'PW': pw_receive,
        'image': image_receive,
        'postwrite_pk': []

    }
    db.user.insert_one(doc)
    return jsonify({'msg': '가입 완료되었습니다!'})

@bp.route('/get', methods=["GET"])
def register_get():
    user_list = list(db.user.find({}, {'_id': False}))
    return jsonify({'user': user_list})

proj/views/login_views.py
from flask import Blueprint, render_template, request, jsonify, session, redirect, url_for
from pymongo import MongoClient

client = MongoClient('mongodb+srv://mino:mino@hanghae.hfuwmwd.mongodb.net/?retryWrites=true&w=majority')
db = client.hanghae

bp = Blueprint('login', __name__, url_prefix='/login')


@bp.route('/home')
def index():
    if 'id' in session:
        return redirect(url_for('main.home'))
    return render_template('login.html')

@bp.route('/reigster')
def register():
    return render_template('register.html')

@bp.route('/', methods=["GET"])
def login_get():
    user_list = list(db.user.find({}, {'_id': False}))
    return jsonify({'user': user_list})


@bp.route('/session', methods=["GET", "POST"])
def login_session():
    if request.method == 'POST':
        # 사용자 아이디를 세션에 저장 및  main으로 리다이렉트
        session.clear();
        session['id'] = request.form['id_give']
        return redirect(url_for('main.home'))


@bp.route('/logout')
def logout():
    # 사용자 아이디를 세션에서 제거하고 /로 리다이렉트
    session.clear();
    return redirect(url_for('login.index'))

proj/views/main_views.py
from flask import Flask, render_template, request, jsonify , session, Blueprint, redirect, url_for

from pymongo import MongoClient
client = MongoClient('mongodb+srv://mino:mino@hanghae.hfuwmwd.mongodb.net/?retryWrites=true&w=majority')
db = client.hanghae

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def home():
    if session.get('id') is None:
        return render_template('login.html')
    image = db.user.find_one({'id': session['id']})['profile']
    return render_template('main.html', user_id=session['id'], profile =image)
   # if 'id' in session :
   #     return render_template('main.html')
   # return render_template('login.html')

#피드게시물표기
@bp.route("/main", methods=["GET"])
def postwrite_get():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_list = list(db.postwrite.find({}, {'_id': False}))

    return jsonify({'post_list': postwrite_pk_list})

@bp.route("/like/count", methods=["GET"])
def like_count_get():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.args.get('postwrite_pk1_give')
    like_list = list(db.like.find({'postwrite_pk': int(postwrite_pk_receive)}, {'_id': False}))
    like_count = len(like_list)

    return jsonify({'like_count': like_count})




# 최신순 좋아요순 정렬 정리
#def home(request):
#   sort = request.GET.get('sort', '')
#   if sort == 'likes':
#      content_list = Content.objects.all().order_by('-like_count', '-date')
#   elif sort == 'comments':
#      content_list = Content.objects.all().order_by('-comment_count', '-date')
#   else:
#      content_list = Content.objects.all().order_by('-date')
#
#   paginator = Paginator(content_list, 5)
#   page = request.GET.get('page', '')
#   posts = paginator.get_page(page)
#   board = Board.objects.all()

#   return render(request, 'home.html', {'posts': posts, 'Board': board, 'sort': sort})






#   import gridfs

   # Create an object of GridFs for the above database.
#   fs = gridfs.GridFS(db)

   # define an image object with the location.
#   file = "testphoto.jpeg"

   # Open the image in read-only format.
#   with open(file, 'rb') as f:
#       contents = f.read()

   # Now store/put the image via GridFs object.
#   fs.put(contents, filename="testphoto")


## 좋아요 갯수 표시
#@app.route("/like/count", methods=["GET"])
#def like_count_get():
#    postwrite_pk_receive = request.args.get('postwrite_pk1_give')
#    like_list = list(db.Like.find({'postwrite_pk': int(postwrite_pk_receive)}, {'_id': False}))
#    like_count = len(like_list)

#    return jsonify({'like_count': like_count})

proj/views/mypage_views.py
from flask import Blueprint, render_template, url_for
from flask import request, jsonify
from flask import session, g

bp = Blueprint('mypage', __name__, url_prefix='/mypage')

# DB : pymongo, certifi import
from pymongo import MongoClient
import certifi
client = MongoClient("mongodb+srv://mino:mino@hanghae.hfuwmwd.mongodb.net/?retryWrites=true&w=majority", tlsCAFile=certifi.where())
db = client.hanghae

@bp.route('/')
def index():
    if session.get('id') is None:
        return render_template('login.html') # 로그인 정보가 없을 때 로그인 페이지로 돌아가게 경로 설정
    g.userid = session['id']
    image = db.user.find_one({'id':session['id']})['profile']
    g.userimg = image
    return render_template('mypage.html')

@bp.route('/userpost', methods=["GET"])
def pass_user_posts() :
    if session.get('id') is None:
        return render_template('login.html')

    user_posts = list(db.postwrite.find({'user_pk':session['id']},{'_id':False}))
    return jsonify(user_posts)

@bp.route('/bookmark', methods=["GET"])
def pass_user_bookmarks() :
    if session.get('id') is None:
        return render_template('login.html')
    postwrite_list = list(db.bookmark.find({'bookmark_id':session['id']}, {'_id':False}))
    result = []
    for num in range(len(postwrite_list)):
        postwrite_pk = postwrite_list[num]['postwrite_pk']
        tmp = db.postwrite.find_one({'postwrite_pk':postwrite_pk},{'_id':False})
        result.append(tmp)
    return jsonify(result)

@bp.route('/comment', methods=["GET"])
def pass_user_comments() :
    if session.get('id') is None:
        return render_template('login.html')

    user_posts_pk = list(db.postwrite.find({'user_pk':session['id']},{'_id':False, 'postwrite_pk':True}))
    result = []
    for num in range(len(user_posts_pk)):
        postwrite_pk = user_posts_pk[num]['postwrite_pk']
        tmp = list(db.comment.find({'postwrite_pk':postwrite_pk},{'_id':False}))
        if tmp:
            db.comment.update_many({'postwrite_pk':postwrite_pk},{'$set':{'comments_flag' : False}})
            result.append(tmp)
    return jsonify(result)

@bp.route('/like', methods=["GET","POST"])
def pass_user_likes() :
    if session.get('id') is None:
        return render_template('login.html')

    user_posts_pk = list(db.postwrite.find({'user_pk':session['id']},{'_id':False, 'postwrite_pk':True}))
    result = []
    for num in range(len(user_posts_pk)):
        postwrite_pk = user_posts_pk[num]['postwrite_pk']
        tmp = list(db.like.find({'postwrite_pk':postwrite_pk},{'_id':False}))
        if tmp:
            result.append(tmp)
            db.like.update_many({'postwrite_pk':postwrite_pk},{'$set':{'like_flag' : False}})
    return jsonify(result)


@bp.route('/postpage')
def postpage() :
    if session.get('id') is None:
        return render_template('login.html')
    return render_template('postpage.html')

proj/views/post_views.py
from pymongo import MongoClient
client = MongoClient('mongodb+srv://mino:mino@hanghae.hfuwmwd.mongodb.net/?retryWrites=true&w=majority')
db = client.hanghae

from flask import Flask, render_template, request, jsonify, session, Blueprint, url_for, g

bp = Blueprint('post', __name__, url_prefix='/post')

@bp.route('/<post>', methods=["GET","POST"])
def home(post):
    if session.get('id') is None:
        return render_template('login.html')
    post_pk = post
    return render_template('post.html', post_pk = post_pk)

# 포스트 불러오기
@bp.route("/get", methods=["GET"])
def post_get():
    if session.get('id') is None:
        return render_template('login.html')
    postwrite_pk_receive = request.args.get('postwrite_pk1_give')
    postwrite_list = list(db.postwrite.find({'postwrite_pk': int(postwrite_pk_receive)}, {'_id': False}))

    user = db.postwrite.find_one({'postwrite_pk':int(postwrite_pk_receive)})['user_pk']
    profile = db.user.find_one({'id':user})['profile']
    postwrite_list.append(profile)

    return jsonify({'post_list': postwrite_list})

# 댓글 데이터 저장
@bp.route('/comment', methods=["POST"])
def comment():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.form['postwrite_pk_give']
    comments_receive = request.form['comments_give']
    comments_date_receive = request.form['comments_date_give']

    # pk용 카운트 만들기
    box = list(db.counts.find({}))
    num = box[0]['comment_count']
    db.counts.update_one({}, {'$set': {'comment_count': num + 1}})

    doc = {
        'postwrite_pk': int(postwrite_pk_receive),
        'comments_pk': num+1,
        'comments': comments_receive,
        'comments_flag': True,
        # 접속유저 pk(세션)
        'comments_id': session['id'],
        'comments_date': comments_date_receive,
    }
    db.comment.insert_one(doc)

    return jsonify({'msg': '댓글 작성 완료!'})

# 댓글 불러오기
@bp.route("/comment", methods=["GET"])
def comment_get():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.args.get('postwrite_pk1_give')
    comment_list = list(db.comment.find({'postwrite_pk': int(postwrite_pk_receive)}, {'_id': False}))

    return jsonify({'comment_list': comment_list})

# 댓글 갯수 표시
@bp.route("/comment_count", methods=["GET"])
def comment_count_get():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.args.get('postwrite_pk1_give')
    comment_list = list(db.comment.find({'postwrite_pk': int(postwrite_pk_receive)}, {'_id': False}))

    comment_count = len(comment_list)
    return jsonify({'comment_count': comment_count})

# 댓글 삭제
@bp.route('/comment/delete', methods=["POST"])
def comment_delete():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.form['postwrite_pk_give']
    comment_pk_receive = request.form['comment_pk_give']

    # 포스트작성자권한
    postwrite_pk1 = db.postwrite.find_one({'postwrite_pk': int(postwrite_pk_receive)}, {'_id': False})
    postwrite_pk2=postwrite_pk1['user_pk']

    # 댓글작성자권한
    if (db.comment.find_one({'comments_pk': int(comment_pk_receive),'comments_id':session['id']})):
        db.comment.delete_one({'comments_pk': int(comment_pk_receive)})
        return jsonify({'msg': '댓글 삭제!'})
    # 포스트작성자권한
    elif (session['id'] == postwrite_pk2):
        db.comment.delete_one({'comments_pk': int(comment_pk_receive)})
        return jsonify({'msg': '댓글 삭제!'})
    else:
        return jsonify({'msg': '권한이 없습니다!'})


# 좋아요 데이터 저장
@bp.route('/like', methods=["POST"])
def like():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.form['postwrite_pk_give']

    # pk용 카운트 만들기, 좋아요 데이터 저장
    box = list(db.counts.find({}))
    num = box[0]['like_count']
    db.counts.update_one({}, {'$set': {'like_count': num + 1}})

    doc = {
        'postwrite_pk': int(postwrite_pk_receive),
        'like_pk': num+1,
        'like_flag': True,
        # 접속유저 pk값(세션)
        'like_id': session['id']
    }
    db.like.insert_one(doc)

    # 좋아요 갯수 추가

    post = db.postwrite.find_one({'postwrite_pk': int(postwrite_pk_receive)})
    db.postwrite.update_one({'postwrite_pk':int(postwrite_pk_receive)},{'$set':{'like':post['like']+1}})

    return jsonify({'msg': '좋아요!'})

# 좋아요 눌럿으면 채운하트 아니면 빈하트
@bp.route("/like", methods=["GET"])
def like_get():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.args.get('postwrite_pk1_give')

    if db.like.find_one({'like_id': session['id'],'postwrite_pk': int(postwrite_pk_receive)}):
        return jsonify({'result': 1})
    else:
        return jsonify({'result': 0})

# 좋아요 갯수 표시
@bp.route("/like/count", methods=["GET"])
def like_count_get():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.args.get('postwrite_pk1_give')
    like_list = list(db.like.find({'postwrite_pk': int(postwrite_pk_receive)}, {'_id': False}))
    like_count = len(like_list)

    return jsonify({'like_count': like_count})

# 좋아요 취소
@bp.route('/like/delete', methods=["POST"])
def like_delete():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.form['postwrite_pk_give']

    db.like.delete_one({'like_id': session['id'],'postwrite_pk': int(postwrite_pk_receive)})

    post = db.postwrite.find_one({'postwrite_pk': int(postwrite_pk_receive)})
    db.postwrite.update_one({'postwrite_pk':int(postwrite_pk_receive)},{'$set':{'like':post['like']-1}})

    return jsonify({'msg': '좋아요 취소!'})

# 북마크 데이터 저장
@bp.route('/bookmark', methods=["POST"])
def bookmark():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.form['postwrite_pk_give']

    # pk용 카운트 만들기
    box = list(db.counts.find({}))
    num = box[0]['bookmark_count']
    db.counts.update_one({}, {'$set': {'bookmark_count': num + 1}})

    doc = {
        'bookmark_pk': num+1,
        'postwrite_pk': int(postwrite_pk_receive),
        # 접속유저 pk값(세션)
        'bookmark_id': session['id']
    }
    db.bookmark.insert_one(doc)

    return jsonify({'msg': '북마크!'})

# 북마크 눌렀으면 채운 북마크 아니면 빈 북마크
@bp.route("/bookmark", methods=["GET"])
def bookmark_get():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.args.get('postwrite_pk1_give')

    if db.bookmark.find_one({'bookmark_id': session['id'], 'postwrite_pk': int(postwrite_pk_receive)}):
        return jsonify({'result': 1})
    else:
        return jsonify({'result': 0})
# 북마크 취소
@bp.route('/bookmark/delete', methods=["POST"])
def bookmark_delete():
    if session.get('id') is None:
        return render_template('login.html')

    postwrite_pk_receive = request.form['postwrite_pk_give']

    db.bookmark.delete_one({'bookmark_id': session['id'],'postwrite_pk':int(postwrite_pk_receive)})
    return jsonify({'msg': '북마크 취소!'})

proj/views/postwrite.py
from pymongo import MongoClient
client = MongoClient('mongodb+srv://mino:mino@hanghae.hfuwmwd.mongodb.net/?retryWrites=true&w=majority')
db = client.hanghae

from flask import render_template, request, jsonify
from flask import Blueprint, url_for, session, g

bp = Blueprint('postwrite', __name__, url_prefix='/postwrite')

@bp.route('/', methods=["POST"])
def postwrite():
    image_receive = request.form['image_give']
    tags_receive = request.form['tags_give']
    text_receive = request.form['text_give']
    write_date_receive = request.form['write_date_give']

    # pk용 카운트 만들기
    box = list(db.counts.find({}))
    num = box[0]['count_pk']
    db.counts.update_one({}, {'$set': {'count_pk': num + 1}})

    doc = {
        'postwrite_pk': num+1,
        'user_id': session['id'],
        'tags': tags_receive.split(' '),
        'text': text_receive,
        'image': image_receive,
        'write_date': write_date_receive,
    }
    db.postwrite.insert_one(doc)

    return jsonify({'msg': '게시완료!'})


@bp.route("/", methods=["GET"])
def bucket_get():
    user_list = list(db.user.find({'id': session['id']}, {'_id': False}))
    return jsonify({'user': user_list})

proj/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta property="og:title" content="항해99 GRAM" />
    <meta property="og:description" content="항해99분들 서로를 소개해보아요!" />
    <meta property="og:image" content="https://i.esdrop.com/d/f/whRz5ypjfJ/61BdphrWO3.png" />
    <!--AJAX 설정-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- font 불러오기 -->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <!-- CSS 연결 -->
    <link rel="stylesheet" href="{{url_for('static', filename='login.css')}}"/>
    <title>로그인 - 항해99 GRAM</title>
</head>

<body>
<div class="login_wrapper">
    <h1>항해99 GRAM</h1>
    <form class="login_form" action="#">
        <input type="text" id="LOGIN_ID" name="id" onkeydown="onlyAlphabet(this)" placeholder="ID">
        <div id="VERI_ID" class="msg"></div>
        <input type="password" id="LOGIN_PW" name="id" onkeydown="onlyAlphabet(this)" placeholder="PASSWORD">
        <div id="VERI_PW" class="msg"></div>
        <button id="LOGIN_BTN" type="button" disabled>로그인</button>
    </form>
    <div class="signup">
        <a href="{{ url_for('login.register') }}">회원가입</a>
    </div>
</div>

<!-- sha256을 사용하기 위해 콜(암호화) -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-sha256/0.9.0/sha256.min.js"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='login.js') }}"></script>
</body>

</html>

proj/templates/main.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" ,>

    <meta property="og:title" content="항해99 GRAM" />
    <meta property="og:description" content="항해99분들 서로를 소개해보아요!" />
    <meta property="og:image" content="https://i.esdrop.com/d/f/whRz5ypjfJ/61BdphrWO3.png" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <title>항해99 GRAM</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>


<style>
    .all {


    }

    /*로고여백*/
    .top {
        margin: 20px 20px 20px 20px;
        padding: 0px 0px 0px 0px;
        border-bottom: solid 2px whitesmoke;


    }

    /*로고*/
    .logo {
        color: gray;
        height: 60px;
        margin: auto;
        font-size: 35px;
        text-align: center;
        width: 400px;


    }

    /*뒤로가기버튼*/
    .back-btn {
        border: 10px solid transparent;
        border-radius: 18px;
        font-size: 30px;
        position: fixed;
    }

    /*유저아이디*/
    .userid {
        float: right;
        margin-right: 10%;
        margin-top: 50px;
        margin-left: 8px;
        font-size: 25px;
    }

    /*프로필버튼 마이페이지 이동 */
    .profile {
        overflow: hidden;
        float: right;
        width: 135px;
        height: 135px;
        border-radius: 100%;
        border:none;


    }

    /*프로필사진*/
    .profile-photo {

        width: 135px;

        height: 135px;

        color: red;
        margin-left: -6px;

        object-fit: cover;
        border-radius: 100px;


    }


    /*사이여백*/
    .middle {
        margin-bottom: 255px;

    }

    /*정렬버튼*/
    .npbutton {

        margin-left: 125px;
        margin-bottom: 10px;
        margin-top: 10px;
        width: 95%;
    }

    /*정렬버튼 상단 줄*/
    .classificaftion {

        width: 100%;
        border-top: solid 2px whitesmoke;


    }

    /*게시버튼*/
    .upload {
        margin-left: 70%;


        background-color: white;

        border: none;
        font-size: 28px;
    }

    /*로그아웃*/
    .Logout {
        background-color: ghostwhite;
        margin-left: 95%;
        border: gray;
    }

    /*게시물박스*/
    .posts-box {



    }

    /*게시물*/
    .post {
        float: left;
        margin-right: 2%;
        margin-left: 8%;
        margin-top:15px;
        margin-bottom: 15px;
        display: flex;
        flex-wrap:wrap;





    }

    /*좋아요버튼*/
    .like {
        border: none;
        background-color: white;
        margin-left: 90%;
        font-size: 23px;
    }

    /*게시물사진*/
    .card {
        width: 530px;
        height: auto;


    }

</style>

<script>
    $(document).ready(function () {
        show_post();
    });

    function show_post() {
        $.ajax({
            type: "GET",
            url: "/main",
            data: {},
            success: function (response) {
                let rows = response['post_list']
                    console.log(rows)
                for (let i = rows.length-1; i >= 0; i--) {
                    let id = rows[i]['user_pk']
                    let text = rows[i]['text']
                    let tags = rows[i]['tags']
                    let image = rows[i]['image']
                    let write_time = rows[i]['write_date']
                    let like = rows[i]['like']
                    let post = rows[i]['postwrite_pk']

                    let the_present_date = new Date();
                    let posts_write_time = new Date(write_time)
                    let time_comparison = the_present_date.getTime() - posts_write_time.getTime()

                    if ((time_comparison / (1000 * 60)) < 60) {
                        time = (time_comparison / (1000 * 60))
                        temp_time = `${parseInt(time)}분 전`
                    } else if ((time_comparison / (1000 * 60 * 60)) < 24) {
                        time = (time_comparison / (1000 * 60 * 60))
                        temp_time = `${parseInt(time)}시간 전`
                    } else {
                        time = (time_comparison / (1000 * 60 * 60 * 24))
                        temp_time = `${parseInt(time)}일 전`
                    }

                    let temp_post = `<div id="post" class="post">
                                    <div class="card">
                                <div class="postimg">
                                    <a href='/post/${post}?post=${post}'>
                                        <img class="card-img-top" src=${image}
                                           alt="...">  </div>
                                    </a>
                                <div class="card-body">
                                    <h5 class="card-title">${id}</h5>
                                    <button class="like">♡️<h9>${like}</h9></button>
                                    <p class="card-text">${text}</p>
                                    <a href='#' class="card-text">  #${tags}   </a>
                                    <p> ${temp_time} </p>
                                </div></div></div>`
                    $('#post').append(temp_post)
                }
            }
        });
    }


</script>


<body>
<div class="all">
    <!--로고-->
    <div style="float:top;" class='top'>
        <button onclick="location.href='login/logout'" class="Logout">Logout</button>
        <h1 class='logo'>항해99 GRAM</h1>
    </div>
    <!--뒤로가기 버튼-->
{#    <div>#}
{#        <button onclick="history.back()" type="button" class="back-btn">🔙</button>#}
{#    </div>#}
    <!--유저아이디 및 프로필-->
    <div>
        <h1 class="userid"> {{ user_id }} </h1> <!--comments_id -->
        <!-- comments_profile / 마이페이지 이동 -->
        <button onclick="location.href='mypage'" class="profile" type="button"><img class="profile-photo"
                                                                                       src= {{ profile }}>
            <!--프로필-->
        </button>
    </div>
    <div class="middle"> <!--사이공백-->
    </div>

    <div class="classificaftion">
        <div class="npbutton"> <!--정렬버튼-->
            <button type="button" class="btn btn-success">NEW</button>
            <button type="button" class="btn btn-danger">POPULAR</button>
            <!--게시물 작성 페이지 이동-->
            <button onclick="location.href='postwrite/page'" class="upload" type="button" class="btn btn-dark">➕</button>
        </div>
    </div>
    <!--게시물박스-->
<div class="posts-box">
    <div id="post" class="post">

    </div>
</div>


</div>


</div>

</div>
</body>
</html>

proj/templates/postpage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  test를 위한 페이지입니다.

  <script type="text/javascript">
    const searchParams = new URLSearchParams(location.search);
    for (const param of searchParams) {
      console.log(param);
    }
  </script>
</body>

</html>